channels:
- conda-forge
dependencies:
- python=3.9.17
- pip<=23.2.1
- pip:
  - mlflow==2.6.0
  - cffi==1.15.1
  - cloudpickle==2.2.1
  - matplotlib==3.7.2
  - numpy==1.24.3
  - packaging==23.0
  - scikit-learn==1.3.0
name: mlflow-env
